version: '3'
services:

  # elasticsearch instance, should be available at http://localhost:9200/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - discovery.type=single-node
    networks:
      - docker-network
    ports:
      - 9200:9200
      - 9300:9300

  # kibana instance, should be available at http://localhost:5601/
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    depends_on:
      - elasticsearch
    networks:
      - docker-network
    ports:
      - 5601:5601

networks:
  docker-network:
    driver: bridge
