sources:
  - source: github
    repositories:
      from: list
      list:
        - name: wlezzar/jtab
        - name: wlezzar/doks
        - name: adevinta/zoe
      # By default, all markdown files are indexed (.md). You can choose what files to include instead
      # include:
      #   - '^.*\.txt$'

  ## Google drive documents source: scans google drive and uses scans google docs.
  # - source: googleDrive
  #   secretFile: /path/to/secret

# Search engine to use (default is lucene)
engine:
  use: lucene
