# sources to fetch documents from
sources:
  - id: github
    source: github
    repositories:
      from: list
      list:
        - name: wlezzar/jtab
        - name: wlezzar/doks
        - name: adevinta/zoe

# Search engine to use
engine:
  use: lucene
